#include "scripts\base.inc"

global WinMenu;

#include "interface\verbbar\verbbar_functions.inc"

var verb_default = "Look at";

////////////////////////////////////////////////////////////////////////////////
on "LookAt"
{
  verb_setBar(Command.Verb + " "+self.Caption);

  GoToObject();

  Game.Interactive=false;

  actor.Talk("This parchment appears to contain some kind of glyphs.");
  actor.Talk("Most are directed toward an individual named Memorandum.");

  verb_cleanBar();

  Game.Interactive=true;
}

////////////////////////////////////////////////////////////////////////////////
on "TalkTo"
{
  verb_setBar(Command.Verb + " "+self.Caption);

  GoToObject();

  Game.Interactive=false;

  actor.Talk("I don't know how to communicate with that.");

  verb_cleanBar();

  Game.Interactive = true;
}

////////////////////////////////////////////////////////////////////////////////
on "PickUp"
{
  verb_setBar(Command.Verb + " "+self.Caption);

  GoToObject();
  
  Game.Interactive=false;

  actor.Talk("I don't need that.");

  verb_cleanBar();

  Game.Interactive=true;
}

////////////////////////////////////////////////////////////////////////////////
on "Use"
{
  verb_setBar(Command.Verb + " "+self.Caption);

  GoToObject();

  Game.Interactive=false;

  actor.Talk("I don't know how to operate that.");
  
  verb_cleanBar();

  Game.Interactive=true;
}

////////////////////////////////////////////////////////////////////////////////
on "Give"
{
  verb_setBar(Command.Verb + " "+self.Caption);
  
  verb_cleanBar();

}

////////////////////////////////////////////////////////////////////////////////
on "Smell"
{
  verb_setBar(Command.Verb + " "+self.Caption);

  GoToObject();

  Game.Interactive=false;

  actor.Talk("The substance fused to this parchment possesses an interesting aroma.");
  
  verb_cleanBar();

  Game.Interactive=true;
}

////////////////////////////////////////////////////////////////////////////////
on "Open"
{
  verb_setBar(Command.Verb + " "+self.Caption);

  GoToObject();

  Game.Interactive=false;

  actor.Talk("That doesn't seem to open.");
  
  verb_cleanBar();

  Game.Interactive=true;
}

////////////////////////////////////////////////////////////////////////////////
on "Move"
{
  verb_setBar(Command.Verb + " "+self.Caption);

  GoToObject();

  Game.Interactive=false;

  actor.Talk("Moving that would accomplish nothing.");
  
  verb_cleanBar();

  Game.Interactive=true;
}

////////////////////////////////////////////////////////////////////////////////
on "gun"
{
  verb_setBar(Command.Verb + " "+self.Caption);

  GoToObject();

  Game.Interactive=false;

  actor.Talk("I don't need to shoot that.");
  
  verb_cleanBar();

  Game.Interactive=true;
}

////////////////////////////////////////////////////////////////////////////////
on "gun"
{
  verb_setBar(Command.Verb + " "+self.Caption);

  GoToObject();

  Game.Interactive=false;

  actor.Talk("Doesn't look like that takes keycards.");
  
  verb_cleanBar();

  Game.Interactive=true;
}

////////////////////////////////////////////////////////////////////////////////
on "batteries"
{
  verb_setBar(Command.Verb + " "+self.Caption);

  GoToObject();

  Game.Interactive=false;

  actor.Talk("I don't know what to do with those.");
  
  verb_cleanBar();

  Game.Interactive=true;
}

////////////////////////////////////////////////////////////////////////////////
on "LeftClick"
{
  if(Command.Verb == "")
  {
    GoToObject();
  }
}

////////////////////////////////////////////////////////////////////////////////
on "RightClick"
{
  verb_apply(verb_default);
}

////////////////////////////////////////////////////////////////////////////////
on "MouseEntry"
{
  verb_hover("Look at");
}

////////////////////////////////////////////////////////////////////////////////
on "MouseLeave"
{
  verb_unhover("Look at");
}

function GoToObject()
{
actor.GoTo(83, 90);
actor.TurnTo(DI_LEFT);
}

