#include "scripts\base.inc"

global WinMenu;

#include "interface\verbbar\verbbar_functions.inc"

var verb_default = "Look at";

////////////////////////////////////////////////////////////////////////////////
on "LookAt"
{
  verb_setBar(Command.Verb + " " + Command.Object1_caption);
  Game.Interactive = false;

  actor.Talk("A crude ballistic firearm fashioned from a primitive alloy.");
  verb_cleanBar();
  Game.Interactive = true;
}

////////////////////////////////////////////////////////////////////////////////
on "TalkTo"
{
  verb_setBar(Command.Verb + " " + Command.Object1_caption);
  Game.Interactive = false;

  actor.Talk("I don't know how to communicate with that.");
  verb_cleanBar();
  Game.Interactive = true;
}

////////////////////////////////////////////////////////////////////////////////
on "Smell"
{
  verb_setBar(Command.Verb + " " + Command.Object1_caption);
  Game.Interactive = false;

  actor.Talk("That has no odour.");
  verb_cleanBar();
  Game.Interactive = true;
}

////////////////////////////////////////////////////////////////////////////////
on "Open"
{
  verb_setBar(Command.Verb + " " + Command.Object1_caption);
  Game.Interactive = false;

  actor.Talk("That doesn't seem to open.");
  verb_cleanBar();
  Game.Interactive = true;
}

////////////////////////////////////////////////////////////////////////////////
on "ammunition"
{
  verb_setBar(Command.Verb + " " + Command.Object1_caption);
  Game.Interactive = false;
  Game.PlaySound("sound\sound12.wav");
  actor.Talk("The weapon has been loaded.");
  Game.DropItem("ammunition");
  LoadedWeapon = true;
  verb_cleanBar();
  Game.Interactive = true;
}

////////////////////////////////////////////////////////////////////////////////
on "carol"
{
  verb_setBar(Command.Verb + " " + Command.Object1_caption);
  Game.Interactive = false;

  actor.Talk("Terminating this lifeform could attract unwarranted attention.");
  verb_cleanBar();
  Game.Interactive = true;
}

////////////////////////////////////////////////////////////////////////////////
on "zif_aimless"
{
  verb_setBar(Command.Verb + " "+self.Caption);
  Game.Interactive=false;

if(Command.Verb == "Use")
  {
  actor.Talk("I don't need to shoot him.");
  } 
if(Command.Verb == "Give")
  {
  actor.Talk("And lose my advantage?");
  }

  verb_cleanBar();
  Game.Interactive=true;
}

////////////////////////////////////////////////////////////////////////////////

on "PickUp"
{
  verb_cleanBar();
}

////////////////////////////////////////////////////////////////////////////////

on "Move"
{
  verb_cleanBar();
}

////////////////////////////////////////////////////////////////////////////////
on "RightClick"
{
  verb_apply(verb_default);
}

////////////////////////////////////////////////////////////////////////////////
on "MouseEntry"
{
  verb_hover("Look at");
}

////////////////////////////////////////////////////////////////////////////////
on "MouseLeave"
{
  verb_unhover("Look at");
}
