#include "scripts\base.inc"

global WinMenu;

#include "interface\verbbar\verbbar_functions.inc"

var verb_default = "Look at";

////////////////////////////////////////////////////////////////////////////////
on "LookAt"
{
  verb_setBar(Command.Verb + " " + Command.Object1_caption);
  Game.Interactive = false;

  actor.Talk("They used to power the hand scanner.");
  verb_cleanBar();
  Game.Interactive = true;
}

////////////////////////////////////////////////////////////////////////////////
on "Smell"
{
  verb_setBar(Command.Verb + " " + Command.Object1_caption);
  Game.Interactive = false;

  actor.Talk("Mmm, acidy.");
  verb_cleanBar();
  Game.Interactive = true;
}

////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
on "ammunition"
{
  verb_setBar(Command.Verb + " " + Command.Object1_caption);
  Game.Interactive = false;
  Game.PlaySound("sound\sound12.wav");
  actor.Talk("The weapon has been loaded.");
  Game.DropItem("ammunition");
  LoadedWeapon = true;
  verb_cleanBar();
  Game.Interactive = true;
}


on "PickUp"
{
  verb_cleanBar();
}

////////////////////////////////////////////////////////////////////////////////


on "Move"
{
  verb_cleanBar();
}

////////////////////////////////////////////////////////////////////////////////
on "RightClick"
{
  verb_apply(verb_default);
}

////////////////////////////////////////////////////////////////////////////////
on "MouseEntry"
{
  verb_hover("Look at");
}

////////////////////////////////////////////////////////////////////////////////
on "MouseLeave"
{
  verb_unhover("Look at");
}
